plugins {
    id 'base'
}

ext {
    isWindows = org.gradle.internal.os.OperatingSystem.current().isWindows()
    pythonExec = isWindows ? file('.venv/Scripts/python.exe').absolutePath : file('.venv/bin/python').absolutePath
}

task test(type: Exec) {
    group = 'verification'
    description = 'Runs Python tests using pytest'
    commandLine pythonExec, '-m', 'pytest'
}

task checkLint(type: Exec) {
    group = 'verification'
    description = 'Runs Python linter using ruff'
    commandLine pythonExec, '-m', 'ruff', 'check', '.'
}

check.dependsOn test, checkLint

