plugins {
    id 'base'
}

task test(type: Exec) {
    group = 'verification'
    description = 'Runs Python tests using pytest'
    commandLine 'uv', 'run', 'pytest'
}

task checkLint(type: Exec) {
    group = 'verification'
    description = 'Runs Python linter using ruff'
    commandLine 'uv', 'run', 'ruff', 'check', '.'
}

check.dependsOn test, checkLint
