"""add_construction_year_sort_index

Revision ID: 17f93a0cedcb
Revises: '006_user_role'
Create Date: 2026-07-29 12:12:14.686457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f93a0cedcb'
down_revision: Union[str, None] = '006_user_role'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_listing_construction_year', 'listing_current', ['lifecycle', 'is_short_term', 'construction_year', 'article_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_listing_construction_year', table_name='listing_current')
    # ### end Alembic commands ###
